OBJ_SRC   = $(wildcard *.c)
CLIENT	  = constants generic task directory memory block file creator filesystem
CRT0      = x86
LIBS      = std
TARGET	  = $(notdir $(shell "pwd"))

include	../Makeconf

all:	$(TARGET)
